### ISSUE TITLE
Add support for PATCH method

### ISSUE THREAD

**Issue by tormi** [tommut/HttpRequester#13]
As per header. Reasoning:

> So, the REST team has concluded that PUT is simply more trouble than it's worth at this point. We therefore propose to drop PUT support from the rest.module entirely and rely on POST and PATCH for write operations.

https://groups.drupal.org/node/284948

**Comment by tormi** [comment]
Well, it's supported, but not that visible option ;) Closing.

**Comment by tommut** [comment]
Thanks. I agree that the UI could definitely make it clearer :)
