### ISSUE TITLE
Question: Filesystem location of stored requests (Linux)

### ISSUE THREAD

**Issue by chefarov** [tommut/HttpRequester#17]
Hi,

Thanks for the addon, it's usefull. I was searching in .mozilla directory to find the saved requests in order to copy them to another machine, with no luck. Could you tell me the location?

Thanks

**Comment by tommut** [comment]
It's actually stored as JSON in Mozilla preferences (which I'm not sure where Mozilla actually stores).
The easiest way to transport saved requests is to type  about:config  in the URL bar of your source machine.
Filter on 'extensions.httprequester.history'  then right-click and select Copy Value.

Then on your target machine go to about:config and go to that preference, right click and select Modify. Copy the value there.

Hope that helps.

**Comment by chefarov** [comment]
Thank you
