### ISSUE TITLE
Problems with Content-Type

### ISSUE THREAD

**Issue by arturbmallmann** [tommut/HttpRequester#25]
Hello, my name is Artur, and i had troubles with the version 2.1.1-signed.1-signed of HttpRequester.
I was having troubles with my JAX-RS(jersey) application:
Just GET method was working, and the response to PUT and POST was ever Code 400(bad request).
I lost many hours trying everything in my code, changed web server, etc..! Then a got some demos and noticed the same thing happened.
I tried my self to do the requisitions by hand and everything just worked.
The problem bothered me out, then i tested a request to netcat:
`
POST /clinicWebBackend/clinicweb/usuarios HTTP/1.1
Host: localhost:1234
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
Accept: application/json
Accept-Language: pt-BR,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Authorization: hmac foo@bar.com:xxxx
Content-Type: application/json, application/json
Content-Length: 70
Connection: keep-alive

    {
        "nome": "nilo",
        "email": "lol@toto.to.to"
    }

`
And the problem was that: Content-Type: application/json, application/json
Every requisition HttpRequester is sending repetitively the same Mime! I had tested with others mimes and this happens every time!

**Comment by ApproximateIdentity** [comment]
I just ran into this same problem. If it haelps, I'm currently running debian 8 Jessie and I ran this with a freshly downloaded Firefox Developer Edition browser. I have the same version of HttpRequester installed as Artur.

A bit of an annoying bug. For me personally if there were an option to _not_ send a Content-Type at all that would be good enough since my backend can still handle that.

Thanks to the author(s)/maintainer(s).

Thomas

**Comment by MEmmanuel** [comment]
Same issue for me. Cannot use it anymore. That's really too bad, it's so useful!  :'(

**Comment by darklynx** [comment]
same here, after Firefox update the HttpRequester sends Content-Type that cannot be parsed/recognized by services due to coma and duplicated value

please, fix asap or I'll need to look for an alternative :(

**Comment by tommut** [comment]
Should be fixed as part of the v2.2. release.
