### ISSUE TITLE
Double Content-Type Header

### ISSUE THREAD

**Issue by alzap** [tommut/HttpRequester#30]
Looks like the new version is doubling the Content-Type Header causing an error 400 from the servers.

For example:
value: 'application/json, application/json'
or 
value: 'text/plain, text/plain'

**Comment by arysin** [comment]
I can confirm this, started to happen recently, my Firefox is 51.0.1

**Comment by BlacKCaT27** [comment]
Just spent 2 hours trying to debug this before realizing it was HttpRequester. Hope it's fixed soon. can verify this is happening to me too

**Comment by yellowanwu** [comment]
me too

**Comment by bjtieman** [comment]
I'm seeing the exact same problem.  Seems related to FireFox 51.0.1.

Is this even a live project anymore?  There's an open pull request that's been open for nearly a year with no response from anyone related to the project :(

**Comment by BlacKCaT27** [comment]
I certainly hope so, as this tools UI blows postman's out of the water imo

**Comment by darklynx** [comment]
same here :( also mentioned in #25

**Comment by michallohnisky** [comment]
+1

**Comment by inthroxify** [comment]
If anyone wants a _temporary_ workaround:
- Install Firefox Developer Edition
- Install HttpResuester Addon
- Type about:config into the URL bar in Firefox
- In the Search box type xpinstall.signatures.required
- Double-click the preference, or right-click and selected "Toggle", to set it to false.
- Type about:support into the URL bar in Firefox
- Under the "Application Basics" section, find "Profile Folder" and click the "Open Folder" button.
- open the "extensions" folder
- open the folder beginning with "{ea4637dc"
- modify HTTP.js in the folder according to the changes specified in #35 
- restart the browser
- use this FF Dev edition for HttpRequester until Tom comes back to life

I don't have twitter. If you found this information useful, please find Tom on twitter and ask him kindly to investigate pull request #35 and publish a new version of the extension.
