### ISSUE TITLE
firefox not update?

### ISSUE THREAD

**Issue by labike** [tommut/HttpRequester#46]
hi, firefox57.0 not support HttpRequester? and author still keep update? thanks!

**Comment by JoshuaBaunach** [comment]
https://github.com/tommut/HttpRequester/issues/44#issuecomment-343206906

The creator understands that HttpRequester is not compatible with the latest version of Firefox, and he has no plans to update it again.

He suggests RESTer as an alternative: https://addons.mozilla.org/en-US/firefox/addon/rester/

**Comment by labike** [comment]
thanks!

**Comment by blentle** [comment]
I sent a post request with json  through RESTER , but the json data didn't pretty that meant it show as one line , The server didn't receive full data ，see:
{"phoneManufacturer":"test","msgNumberList":[{"lastModified":0,"msgNumber":"1001016"}],"areaNumber":"13800138","sysModel":"GN9011","channelId":"1006585400001"}
the server received data below:
],"areaNumber":"13800138","sysModel":"GN9011","channelId":"1006585400001"}

if I sent the json data like this ：
{
    "phoneManufacturer": "test",
    "msgNumberList": [
        {
            "lastModified": 0,
            "msgNumber": "1001016"
        }
    ],
    "areaNumber": "13800138",
    "sysModel": "GN9011",
    "channelId": "1006585400001"
}
The server received correct data .

**Comment by Ryoui** [comment]
no...........

**Comment by carmiroles** [comment]
HttpRequester is a great plugin as rest client.
It's a bad new if it has not been upgraded to new firefox release.

**Comment by VytasLL** [comment]
HttpRequester  was my No.1 tool in development. Now I feel, like kid from witch favorite spoon was taken. :)

**Comment by zicklam** [comment]
Anyone found a nice alternative for this plugin?
